import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const calSans = localFont({
  src: "../public/fonts/CalSans-Regular.ttf",
  variable: "--font-cal-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${calSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
