FROM oven/bun:latest

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/executor ./apps/executor

RUN bun install
RUN bun run db:generate
RUN bun run build

# Executor doesn't expose any port (it's a Kafka consumer/producer)

# CMD [ "bun", "run", "start:executor" ]
