FROM oven/bun:latest

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

ARG DATABASE_URL

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/web ./apps/web

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL}  bun run build

EXPOSE 3000

# TODO: generate prisma client, run migrations, then start server
# CMD [ "bun", "run", "start:web" ]