FROM oven/bun:latest

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/backend ./apps/backend

RUN bun install
RUN bun run db:generate
RUN bun run build

EXPOSE 3004

# TODO: generate prisma client, run migrations, then start server
# CMD [ "bun", "run", "start:backend" ]